### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/money#1]
non la potevi aprire tu? se serve lo puoi fare

**Comment by tonyiovino** [comment]
Sì, ma intendevo su qualche problema che c'è sun "Money".

**Comment by FabioZTessitore** [comment]
```py
importo / 20
```
hai 1063 punti e ancora non hai capito che se fai un'operazione e non salvi il risultato da qualche parte lo perdi???

**Comment by tonyiovino** [comment]
hahahaha, dicevo io...

**Comment by tonyiovino** [comment]
Guardate che non appena incomincia la scuola, mi dovranno di nuovo insegnare a leggere e scrivere...

**Comment by FabioZTessitore** [comment]
eh immagino

**Comment by tonyiovino** [comment]
Penso che si faccia così...
(Devo spegnere il sistema, quindi salvo, anche se non ho finito)

**Comment by FabioZTessitore** [comment]
la strada è giusta

**Comment by tonyiovino** [comment]
Ora mi rimetto a lavoro.

**Comment by tonyiovino** [comment]
Non riesco!

**Comment by tonyiovino** [comment]
Se provo il numero 36 il risultato è 1.6, invece di 1.

**Comment by tonyiovino** [comment]
Okay, ho visto un video su YT (https://www.youtube.com/watch?v=mTebxFc4aPY)

**Comment by FabioZTessitore** [comment]
in py3 la divisione è sempre tra float (anche se i numeri sono int). Per ottenere il risultato intero o fai il cast oppure usi l'operatore `//` come hai fatto.
Ora andiamo avanti

**Comment by tonyiovino** [comment]
Certo!
