### ISSUE TITLE
money

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/money#2]
sulla logica ci siamo, ma il programma non gira.
Devi imparare a farlo funzionare, non solo scrivere quello che ti sembra giusto

**Comment by tonyiovino** [comment]
L'importante e che ho capito come risolverlo.
Ora però non so cos'è che non va... Penso che sia un problema della variabile dell'importo.

**Comment by FabioZTessitore** [comment]
Avere un'idea di come dovrebbe funzionare è solo il primo passo.
Quando sei in difficoltà come in questo caso, usa delle print per stampare i valori che di volta in volta calcoli fino a scoprire dove c'è l'errore

**Comment by tonyiovino** [comment]
Okay, ora ci provo.

**Comment by tonyiovino** [comment]
Solo 10 minuti fa ho mi sono messo all'opera, e cercando di seguire il vostro consiglio, mi sono accorto di un piccolo errore: il "resto_venti/dieci/cinque/uno, erano al contrario. Ora mi sento felice! HAHAHA

**Comment by tonyiovino** [comment]
Ho visto la vostra soluzione... A quanto pare ho trovato ne ho trovata un'altra.

**Comment by FabioZTessitore** [comment]
Si, bravo

Il dom 23 giu 2019, 20:50 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Grazie
